jobs:
  include:
    - stage: test
      language: swift
      os: osx
      osx_image: xcode10.3 # Swift 5.0
      script:
      - swift --version
      - swift build
      - swift test --filter SwiftyBytesTests
      - swift build -c release # Check Release build 
    - stage: test
      language: swift
      os: osx
      osx_image: xcode11.3 # Swift 5.1
      script:
      - swift --version
      - swift build
      - swift test --filter SwiftyBytesTests
      - swift build -c release # Check Release build 
    - stage: test
      language: swift
      os: osx
      osx_image: xcode11.4 # Swift 5.2
      script:
      - swift --version
      - swift build
      - swift test --filter SwiftyBytesTests
      - swift build -c release # Check Release build 
    - stage: test
      language: generic
      os: linux
      dist: bionic
      env:
      - SWIFT_VERSION=5.0
      install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
      - swift --version
      - swift build
      - swift test --filter SwiftyBytesTests
      - swift build -c release # Check Release build 
    - stage: test
      language: generic
      os: linux
      dist: bionic
      env:
      - SWIFT_VERSION=5.1
      install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
      - swift --version
      - swift build
      - swift test --filter SwiftyBytesTests
      - swift build -c release # Check Release build 
    - stage: test
      language: generic
      os: linux
      dist: bionic
      env:
      - SWIFT_VERSION=5.2
      install:
      - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
      - swift --version
      - swift build
      - swift test --filter SwiftyBytesTests
      - swift build -c release # Check Release build 
    - stage: deploy
      if: tag IS present
      language: generic
      os: osx
      osx_image: xcode11.4
     
